apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-ansible-vb-k8-docker-jenkins
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: front-end
          image: git-ansible-vb-k8-docker-jenkins:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: git-ansible-vb-k8-docker-jenkins-svc
spec:
  type: NodePort
  selector:
    app: app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 32500