apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-docker-jenkins-ansible-k8
  labels:
    app: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: front-end
          image: nmm131/flask-docker-jenkins-ansible-k8:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-docker-jenkins-ansible-k8-svc
spec:
  type: NodePort
  selector:
    app: app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 32500