apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-configured
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: front-end
          image: nmm131/jenkins-configured:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-configured-svc
spec:
  type: NodePort
  selector:
    app: web
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 32000