---
# run on Client VM
- hosts: group1
  tasks:
    #- name: install kubernetes
    #  shell: #installation commands go here
    - name: Initialize kubernetes cluster
      # start kubernetes cluster
      shell: minikube start
      register: output
    - name: Clone git project
      shell: |
        if [ -d /home/client/2020_03_DO_Boston_casestudy_part_1 ]
        then
            cd /home/client/2020_03_DO_Boston_casestudy_part_1 && git pull
        else
            git clone https://github.com/nmm131/2020_03_DO_Boston_casestudy_part_1.git /home/client/2020_03_DO_Boston_casestudy_part_1
        fi
      
    - name: Push configuration changes to cluster
      # apply a configuration change to application resource from a file
      command: kubectl apply -f ~/2020_03_DO_Boston_casestudy_part_1/kubernetes-app.yaml