---
- hosts: localhost
  tasks:
    - name: initialize kubernetes cluster
      shell: minikube start
      register: output
      
    - name: copy required files
      shell: mkdir -p ~/.kube
             sudo cp -i /etc/kubernetes/admin.conf ~/.kube/config
             sudo chown $(id -u):$(id -g) ~/.kube/config
      
    - name: kubectl apply
      command: kubectl apply -f ~/2020_03_DO_Boston_casestudy_part_1/playbook.yaml