---
# run on Client VM
- hosts: group1
  tasks:
    #- name: install kubernetes
    #  shell: #installation commands go here
    - name: Initialize kubernetes cluster
      # start kubernetes cluster
      shell: minikube start
      register: output
      
    - name: Push configuration changes to cluster
      # apply a configuration change to application resource from a file
      command: kubectl apply -f kubernetes-app.yaml